# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tautology.town
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  See you 'round; tautology.town 🐸
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tautology.town" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll
# permalink: /posts/:categories/:year/:month/:day/:title:output_ext
permalink: /:categories/:year/:month/:day/:title:output_ext
sass:
  style: compressed
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
